### ISSUE TITLE
Download loop

### ISSUE THREAD

**Issue by sarpba** [cociweb/custom_whisper#6]
I try to install it in a fresh HA x86 install, but:

s6-rc: info: service s6rc-oneshot-runner: starting
s6-rc: info: service s6rc-oneshot-runner successfully started
s6-rc: info: service fix-attrs: starting
s6-rc: info: service fix-attrs successfully started
s6-rc: info: service legacy-cont-init: starting
s6-rc: info: service legacy-cont-init successfully started
s6-rc: info: service whisper: starting
s6-rc: info: service whisper successfully started
s6-rc: info: service discovery: starting
INFO:__main__:Downloading custom model Small to /data
INFO:wyoming_faster_whisper.download:model.bin is downloaded into /data/custom from url: https://huggingface.co/Hungarians/Whisper-small-hu-cleaned/resolve/main/fp32/model.bin
INFO:wyoming_faster_whisper.download:vocabulary.txt is downloaded into /data/custom from url: https://huggingface.co/Hungarians/Whisper-small-hu-cleaned/resolve/main/fp32/vocabulary.txt
INFO:wyoming_faster_whisper.download:config.json is downloaded into /data/custom from url: https://huggingface.co/Hungarians/Whisper-small-hu-cleaned/resolve/main/fp32/config.json
INFO:wyoming_faster_whisper.download:hash.json is downloaded into /data/custom from url: https://huggingface.co/Hungarians/Whisper-small-hu-cleaned/resolve/main/fp32/hash.json
INFO:__main__:Succesfully downloaded the custom model: custom
Traceback (most recent call last):
  File "<frozen runpy>", line 198, in _run_module_as_main
  File "<frozen runpy>", line 88, in _run_code
  File "/usr/local/lib/python3.11/dist-packages/wyoming_faster_whisper/__main__.py", line 182, in <module>
    asyncio.run(main())
  File "/usr/lib/python3.11/asyncio/runners.py", line 190, in run
    return runner.run(main)
           ^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/asyncio/runners.py", line 118, in run
    return self._loop.run_until_complete(task)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/asyncio/base_events.py", line 653, in run_until_complete
    return future.result()
           ^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/dist-packages/wyoming_faster_whisper/__main__.py", line 141, in main
    AsrModel(
TypeError: AsrModel.__init__() missing 1 required positional argument: 'version'
[11:48:24] INFO: Service exited with code 1 (by signal 0)
INFO:__main__:Downloading custom model Small to /data

Download loop contiue forever...

**Comment by cociweb** [comment]
Wierd, every package variation is compromitted with this problem.

**Comment by cociweb** [comment]
V1.1.1 is released. @angmac, @sarpba  Can you please check it?

**Comment by sarpba** [comment]
Everithing fine now! Thank you!

**Comment by angmac** [comment]
v1.1.1 CUDA is OK. Thanks.
