### ISSUE TITLE
Standalone CUDA version loops with python error.

### ISSUE THREAD

**Issue by angmac** [cociweb/custom_whisper#8]
Used docker-compose and logs are attached.
- ha_net is defined elsewhere. 
- in the computer I have 2 nVidia GPU.

[whisper_log.txt](https://github.com/cociweb/custom_whisper/files/14288581/whisper_log.txt)
[docker_compose.txt](https://github.com/cociweb/custom_whisper/files/14288588/docker_compose.txt)

**Comment by angmac** [comment]
Seems it is the same as https://github.com/cociweb/custom_whisper/issues/6

**Comment by cociweb** [comment]
yes, it is the duplicate of #6.
